name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.10
  image_picker: ^0.8.7+4
  persistent_bottom_nav_bar: ^5.0.2
  carousel_slider: ^5.0.0
  auto_size_text: ^3.0.0
  geolocator: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts: 
    - family: Anton
      fonts: 
        - asset: fonts/Anton-Regular.ttf