name: tubes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts: 
    - family: Anton
      fonts: 
        - asset: fonts/Anton-Regular.ttf